CREATE TABLE hr.payroll_history (
    payroll_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   NUMBER REFERENCES hr.employees(employee_id),
    pay_period    DATE, 
    gross_salary  NUMBER,
    tax_amount    NUMBER,
    bonus_amount  NUMBER,
    net_pay       NUMBER,
    status        VARCHAR2(20) 
);


CREATE TABLE hr. salary_config (
    min_salary NUMBER,
    max_salary NUMBER,
    tax_rate   NUMBER 
);
